// routes/ai.js - AI 관련 라우트 (간단 버전)
import express from 'express';
import { protect } from '../middleware/auth.js';

const router = express.Router();

router.use(protect);

// 헬스체크
router.get('/health', async (req, res) => {
    try {
        res.status(200).json({
            success: true,
            ollama: {
                running: false,  // 일단 false로
                models: []
            }
        });
    } catch (error) {
        res.status(500).json({
            success: false,
            message: 'Health check failed'
        });
    }
});

// 코드 생성 (임시 버전)
router.post('/generate-code', async (req, res) => {
    try {
        const { questions, kitId } = req.body;

        // 임시로 간단한 아두이노 코드 반환
        const tempCode = `// Arduino Code - Generated by LABIT
// Kit: ${kitId}

void setup() {
  Serial.begin(9600);
  pinMode(A0, INPUT);  // Sensor
  pinMode(7, OUTPUT);   // LED
  
  Serial.println("System Ready!");
}

void loop() {
  // Read sensor
  int sensorValue = analogRead(A0);
  
  // Print to Serial Monitor
  Serial.print("Sensor: ");
  Serial.println(sensorValue);
  
  // Control LED based on sensor
  if (sensorValue > 500) {
    digitalWrite(7, HIGH);
  } else {
    digitalWrite(7, LOW);
  }
  
  delay(100);
}`;

        res.status(200).json({
            success: true,
            code: tempCode,
            message: '코드가 생성되었습니다 (임시 버전)'
        });
    } catch (error) {
        console.error('Generate code error:', error);
        res.status(500).json({
            success: false,
            message: '코드 생성 중 오류가 발생했습니다'
        });
    }
});

// 코드 설명
router.post('/explain-code', async (req, res) => {
    try {
        const explanation = `이 코드는 다음과 같이 작동합니다:

1. setup() 함수:
   - 시리얼 통신을 9600 baud로 시작합니다
   - A0 핀을 입력(센서)으로 설정합니다
   - 7번 핀을 출력(LED)으로 설정합니다

2. loop() 함수:
   - A0 핀에서 센서 값을 읽습니다 (0-1023 범위)
   - 읽은 값을 시리얼 모니터에 출력합니다
   - 센서 값이 500보다 크면 LED를 켭니다
   - 그렇지 않으면 LED를 끕니다
   - 100ms 대기 후 반복합니다`;

        res.status(200).json({
            success: true,
            explanation
        });
    } catch (error) {
        res.status(500).json({
            success: false,
            message: '코드 설명 생성 중 오류가 발생했습니다'
        });
    }
});

export default router;